name: Build and Test WasmEdge on riscv64 arch

concurrency:
  group: build-riscv64-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build_for_riscv.yml"
      - "include/**"
      - "lib/**"
      - "test/**"
      - "!test/plugins/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    branches:
      - master
      - 'proposal/**'
    paths:
      - ".github/workflows/build_for_riscv.yml"
      - "include/**"
      - "lib/**"
      - "test/**"
      - "!test/plugins/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"

permissions:
  contents: read

jobs:
  # TODO: Refactor `lint` with `on.workflow_run`
  # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
  lint:
    uses: ./.github/workflows/reusable-call-linter.yml

  build_and_test_riscv64:
    name: Build and Test RISC-V64
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        
    - name: Ensure git safe directory
      run: |
        git config --global --add safe.directory $(pwd)
        
    - name: Install RISC-V cross-compilation toolchain
      run: |
        chmod +x utils/setup-riscv-cross.sh
        ./utils/setup-riscv-cross.sh
        
    - name: Cross-compile WasmEdge for RISC-V64
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE=../cmake/riscv64-linux-gnu.cmake \
              -DWASMEDGE_BUILD_TESTS=ON \
              -DWASMEDGE_BUILD_TOOLS=ON \
              -DWASMEDGE_BUILD_SHARED_LIB=ON \
              -DWASMEDGE_USE_LLVM=OFF \
              -DWASMEDGE_BUILD_PLUGINS=OFF \
              ..
        make -j $(nproc)
        
    - name: Package build artifacts for testing
      run: |
        mkdir -p riscv64-artifacts
        # Copy built libraries
        if [ -d "build/lib" ]; then
          cp -r build/lib riscv64-artifacts/
        fi
        # Copy built tools
        if [ -d "build/tools" ]; then
          cp -r build/tools riscv64-artifacts/
        fi
        # Copy test binaries if they exist
        if [ -d "build/test" ]; then
          cp -r build/test riscv64-artifacts/
        fi
        # Copy examples for testing
        cp -r examples riscv64-artifacts/
        # Create a manifest file for debugging
        find riscv64-artifacts -type f -executable > riscv64-artifacts/executable_files.txt
        
    - uses: uraimo/run-on-arch-action@aa8e672a03e10b403401927ea2ceda57e1b68ac3 # v3
      name: Test WasmEdge on RISC-V64 with QEMU
      with:
        arch: riscv64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/workplace"
        shell: /bin/sh
        install: |
          apt-get update -q -y
          apt-get install -q -y wabt coreutils timeout # For WASM tools and test utilities
        run: |
          cd /workplace
          chmod +x utils/test-riscv-qemu.sh
          ./utils/test-riscv-qemu.sh
